<x-super-admin-layout title="Creator Requests">
    <nav aria-label="Creator assistance" class="mb-6 flex flex-wrap gap-2"><a href="{{ route('super-admin.creators.assist',$creator) }}" class="rounded-xl border border-slate-300 px-4 py-2 font-bold">Setup</a><a href="{{ route('super-admin.creators.requests.index',$creator) }}" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Requests</a></nav>
    <div class="mb-6"><h2 class="text-2xl font-extrabold">{{ $creator->display_name }} Requests</h2><p class="text-slate-500">Administrative assistance only. Attribution and ownership are preserved.</p></div>
    <form method="GET" class="mb-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 md:grid-cols-5">
        <input name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Title, URL, Guide, tag, or ID" class="rounded-xl border-slate-300 dark:border-slate-700 dark:bg-slate-950 md:col-span-2">
        <select name="status" class="rounded-xl border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">All statuses</option>@foreach(App\Models\Recommendation::STATUSES as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ App\Models\Recommendation::STATUS_LABELS[$status] }}</option>@endforeach<option value="soft_deleted" @selected(($filters['status']??'')==='soft_deleted')>Soft Deleted</option><option value="spam" @selected(($filters['status']??'')==='spam')>Spam / Removed</option></select>
        <select name="type" class="rounded-xl border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">All content</option>@foreach(['video','playlist','topic','link'] as $type)<option value="{{ $type }}" @selected(($filters['type']??'')===$type)>{{ ucfirst($type) }}</option>@endforeach</select>
        <select name="sort" class="rounded-xl border-slate-300 dark:border-slate-700 dark:bg-slate-950">
            @foreach(['newest'=>'Newest submitted','oldest'=>'Oldest submitted','most_votes'=>'Most votes','least_votes'=>'Least votes','updated'=>'Recently updated','status'=>'Status','published'=>'Published date'] as $value=>$label)
                <option value="{{ $value }}" @selected(($filters['sort'] ?? 'newest') === $value)>{{ $label }}</option>
            @endforeach
        </select>
        <button class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Apply</button>
    </form>
    <div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="p-4">Request</th><th class="p-4">Submitted by</th><th class="p-4">Status</th><th class="p-4">Community impact</th><th class="p-4">Dates</th><th class="p-4">Actions</th></tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">
    @forelse($requests as $item)<tr><td class="p-4"><div class="flex gap-3">@if($item->displayThumbnailUrl())<img src="{{ $item->displayThumbnailUrl() }}" class="h-12 w-20 rounded object-cover" alt="">@else<span class="flex h-12 w-20 items-center justify-center rounded bg-slate-100 text-xs font-bold dark:bg-slate-800">{{ $item->mediaTypeLabel() }}</span>@endif<div><div class="font-bold">#{{ $item->id }} {{ $item->title }}</div><div class="text-xs text-slate-500">{{ $item->mediaTypeLabel() }} @if($item->moderation_reason) · {{ str($item->moderation_reason)->replace('_',' ')->title() }}@endif</div></div></div></td>
    <td class="p-4">{{ $item->isCreatorAdded() ? 'Creator-added' : ($item->submittedBy?->public_display_name ?: $item->submittedBy?->name) }}@unless($item->isCreatorAdded())<div class="text-xs text-slate-500">{{ $item->submittedBy?->email }}</div>@endunless</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{{ $item->trashed() ? 'Soft Deleted' : $item->statusLabel() }}</span></td><td class="p-4">{{ (int)$item->total_vote_quantity }} votes<br>{{ $item->voter_count }} Guides</td><td class="p-4 text-xs">Submitted {{ $item->created_at->format('M j, Y') }}<br>Updated {{ $item->updated_at->format('M j, Y') }}@if($item->published_at)<br>Published {{ $item->published_at->format('M j, Y') }}@endif</td><td class="p-4"><a class="font-bold text-indigo-600" href="{{ route('super-admin.creators.requests.edit',[$creator,$item->id]) }}">{{ $item->trashed() ? 'View / Restore' : 'Edit / Change status' }}</a>@if($item->published_reaction_url)<br><a href="{{ $item->published_reaction_url }}" target="_blank" rel="noopener" class="text-sm text-emerald-600">Open published result</a>@endif</td></tr>
    @empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No requests matched.</td></tr>@endforelse</tbody></table></div><div class="mt-6">{{ $requests->links() }}</div>
</x-super-admin-layout>
