<x-creator-intelligence-layout title="Imports">
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-extrabold">Analytics Imports</h2><p class="ci-muted">YouTube Studio, vidIQ, and prepared CSV history.</p></div><a href="{{ route('superadmin.creator-intelligence.imports.create') }}" class="ci-button-primary">Upload import</a></div>
    <form class="ci-filter-panel mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div><label for="import-channel" class="ci-label text-sm">Channel</label><select id="import-channel" name="creator_channel_id" class="ci-control mt-1 w-full"><option value="">All channels</option>@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected(request('creator_channel_id') == $channel->id)>{{ $channel->channel_name }}</option>@endforeach</select></div>
        <div><label for="import-source-filter" class="ci-label text-sm">Source</label><select id="import-source-filter" name="source" class="ci-control mt-1 w-full"><option value="">All sources</option>@foreach(\App\Enums\ImportBatchSource::cases() as $source)<option value="{{ $source->value }}" @selected(request('source') === $source->value)>{{ str($source->value)->replace('_', ' ')->title() }}</option>@endforeach</select></div>
        <div><label for="import-status" class="ci-label text-sm">Status</label><select id="import-status" name="status" class="ci-control mt-1 w-full"><option value="">All statuses</option>@foreach(\App\Enums\ImportBatchStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ str($status->value)->replace('_', ' ')->title() }}</option>@endforeach</select></div>
        @foreach([['snapshot_from','Snapshot date from'],['snapshot_to','Snapshot date to'],['uploaded_from','Uploaded date from'],['uploaded_to','Uploaded date to']] as [$name,$label])<div><label for="{{ $name }}" class="ci-label text-sm">{{ $label }}</label><input id="{{ $name }}" type="date" name="{{ $name }}" value="{{ request($name) }}" class="ci-control mt-1 w-full"></div>@endforeach
        <div><label for="import-sort" class="ci-label text-sm">Sort imports</label><select id="import-sort" name="sort" class="ci-control mt-1 w-full">@foreach(['created_at'=>'Created At','snapshot_date'=>'Snapshot Date','status'=>'Status','total_rows'=>'Total Rows','failed_rows'=>'Failed Rows'] as $value=>$label)<option value="{{ $value }}" @selected(request('sort','created_at') === $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="flex items-end"><button class="ci-button-primary w-full">Filter imports</button></div>
    </form>
    <div class="ci-table-container" tabindex="0" aria-label="Scrollable analytics imports table"><table class="min-w-full text-sm"><thead><tr class="text-left text-xs uppercase">@foreach(['Created','Channel','Source','File','Snapshot','Status','Rows','Created','Updated','Skipped','Failed','Uploaded by','Actions'] as $heading)<th scope="col" class="p-4">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-200 dark:divide-slate-800">@forelse($batches as $batch)<tr><td class="p-4">{{ $batch->created_at->format('Y-m-d H:i') }}</td><td class="p-4 font-bold">{{ $batch->channel->channel_name }}</td><td class="p-4">{{ $batch->source->value }}</td><td class="max-w-xs truncate p-4"><a class="font-bold text-indigo-700 dark:text-indigo-300" href="{{ route('superadmin.creator-intelligence.imports.show',$batch) }}">{{ $batch->original_filename }}</a></td><td class="p-4">{{ $batch->snapshot_date->toDateString() }}</td><td class="p-4"><a class="font-bold text-indigo-700 dark:text-indigo-300" href="{{ route('superadmin.creator-intelligence.imports.show',$batch) }}">{{ str($batch->status->value)->replace('_',' ')->title() }}</a></td><td class="p-4 text-right">{{ $batch->total_rows }}</td><td class="p-4 text-right">{{ $batch->created_rows }}</td><td class="p-4 text-right">{{ $batch->updated_rows }}</td><td class="p-4 text-right">{{ $batch->skipped_rows }}</td><td class="p-4 text-right">{{ $batch->failed_rows }}</td><td class="p-4">{{ $batch->uploadedBy?->email ?: 'Deleted user' }}</td><td class="p-4"><div class="flex flex-col items-start gap-2"><a class="font-bold text-indigo-700 dark:text-indigo-300" href="{{ route('superadmin.creator-intelligence.imports.show',$batch) }}">View Import</a>@if($batch->status===\App\Enums\ImportBatchStatus::AwaitingMapping)<a class="font-bold text-amber-700 dark:text-amber-300" href="{{ route('superadmin.creator-intelligence.imports.mapping',$batch) }}">Review Mapping</a>@elseif(in_array($batch->status,[\App\Enums\ImportBatchStatus::Failed,\App\Enums\ImportBatchStatus::CompletedWithErrors],true))<a class="font-bold text-rose-700 dark:text-rose-300" href="{{ route('superadmin.creator-intelligence.imports.errors',$batch) }}">View Errors</a>@elseif($batch->status===\App\Enums\ImportBatchStatus::Ready)<form method="POST" action="{{ route('superadmin.creator-intelligence.imports.process',$batch) }}">@csrf<button class="font-bold text-emerald-700 dark:text-emerald-300">Start Processing</button></form>@endif</div></td></tr>@empty<tr><td colspan="13" class="p-8 text-center">No analytics imports yet.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5">{{ $batches->links() }}</div>
</x-creator-intelligence-layout>
