<x-creator-intelligence-layout title="Imports">
    <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-extrabold">Analytics Imports</h2><p class="text-sm text-slate-500">YouTube Studio, vidIQ, and prepared CSV history.</p></div><a href="{{ route('superadmin.creator-intelligence.imports.create') }}" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Upload import</a></div>
    <form class="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-4">
        <select name="creator_channel_id" class="rounded-xl border-slate-300 dark:bg-slate-950"><option value="">All channels</option>@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected(request('creator_channel_id')==$channel->id)>{{ $channel->channel_name }}</option>@endforeach</select>
        <select name="source" class="rounded-xl border-slate-300 dark:bg-slate-950"><option value="">All sources</option>@foreach(\App\Enums\ImportBatchSource::cases() as $source)<option value="{{ $source->value }}" @selected(request('source')===$source->value)>{{ str($source->value)->replace('_',' ')->title() }}</option>@endforeach</select>
        <select name="status" class="rounded-xl border-slate-300 dark:bg-slate-950"><option value="">All statuses</option>@foreach(\App\Enums\ImportBatchStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ str($status->value)->replace('_',' ')->title() }}</option>@endforeach</select>
        <input type="date" name="snapshot_from" value="{{ request('snapshot_from') }}" aria-label="Snapshot date from" class="rounded-xl border-slate-300 dark:bg-slate-950">
        <input type="date" name="snapshot_to" value="{{ request('snapshot_to') }}" aria-label="Snapshot date to" class="rounded-xl border-slate-300 dark:bg-slate-950">
        <input type="date" name="uploaded_from" value="{{ request('uploaded_from') }}" aria-label="Uploaded date from" class="rounded-xl border-slate-300 dark:bg-slate-950">
        <input type="date" name="uploaded_to" value="{{ request('uploaded_to') }}" aria-label="Uploaded date to" class="rounded-xl border-slate-300 dark:bg-slate-950">
        <select name="sort" aria-label="Sort imports" class="rounded-xl border-slate-300 dark:bg-slate-950">@foreach(['created_at'=>'Created At','snapshot_date'=>'Snapshot Date','status'=>'Status','total_rows'=>'Total Rows','failed_rows'=>'Failed Rows'] as $value=>$label)<option value="{{ $value }}" @selected(request('sort','created_at')===$value)>{{ $label }}</option>@endforeach</select>
        <button class="rounded-xl bg-slate-800 px-4 py-2 font-bold text-white">Filter</button>
    </form>
    <div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><table class="min-w-full text-sm"><thead><tr class="text-left text-xs uppercase text-slate-500"><th class="p-4">Created</th><th class="p-4">Channel</th><th class="p-4">Source</th><th class="p-4">File</th><th class="p-4">Snapshot</th><th class="p-4">Status</th><th class="p-4">Rows</th><th class="p-4">Created</th><th class="p-4">Updated</th><th class="p-4">Skipped</th><th class="p-4">Failed</th><th class="p-4">Uploaded by</th><th class="p-4"></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($batches as $batch)<tr><td class="p-4">{{ $batch->created_at->format('Y-m-d H:i') }}</td><td class="p-4 font-bold">{{ $batch->channel->channel_name }}</td><td class="p-4">{{ $batch->source->value }}</td><td class="max-w-xs truncate p-4">{{ $batch->original_filename }}</td><td class="p-4">{{ $batch->snapshot_date->toDateString() }}</td><td class="p-4">{{ str($batch->status->value)->replace('_',' ')->title() }}</td><td class="p-4">{{ $batch->total_rows }}</td><td class="p-4">{{ $batch->created_rows }}</td><td class="p-4">{{ $batch->updated_rows }}</td><td class="p-4">{{ $batch->skipped_rows }}</td><td class="p-4">{{ $batch->failed_rows }}</td><td class="p-4">{{ $batch->uploadedBy?->email ?: 'Deleted user' }}</td><td class="p-4"><a class="font-bold text-indigo-600 dark:text-indigo-300" href="{{ route('superadmin.creator-intelligence.imports.show',$batch) }}">View</a></td></tr>@empty<tr><td colspan="13" class="p-8 text-center text-slate-500">No analytics imports yet.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $batches->links() }}</div>
</x-creator-intelligence-layout>
