<x-creator-intelligence-layout title="Import #{{ $batch->id }}">
    <div class="flex flex-wrap items-start justify-between gap-4">
        <div><h2 class="text-2xl font-extrabold">Import #{{ $batch->id }}</h2><p class="ci-muted mt-1">{{ $batch->original_filename }}</p></div>
        <div class="flex flex-wrap gap-2">@if(in_array($batch->status,[\App\Enums\ImportBatchStatus::Ready,\App\Enums\ImportBatchStatus::AwaitingMapping],true))<a href="{{ route('superadmin.creator-intelligence.imports.mapping',$batch) }}" class="ci-button-secondary">{{ $batch->status===\App\Enums\ImportBatchStatus::AwaitingMapping ? 'Review Mapping' : 'Column Mapping' }}</a>@endif @if($batch->status===\App\Enums\ImportBatchStatus::Ready)<form method="POST" action="{{ route('superadmin.creator-intelligence.imports.process',$batch) }}">@csrf<button class="ci-button-primary">Start Processing</button></form>@endif</div>
    </div>
    <dl class="ci-card mt-6 grid gap-4 text-sm sm:grid-cols-3">@foreach(['Channel'=>$batch->channel->channel_name,'Source'=>$batch->source->value,'Selected CSV'=>$batch->detected_csv_filename ?: 'Pending inspection','Snapshot date'=>$batch->snapshot_date->toDateString(),'Status'=>str($batch->status->value)->replace('_',' ')->title(),'Uploaded by'=>$batch->uploadedBy?->email ?: 'Deleted user','Uploaded at'=>$batch->created_at,'Started at'=>$batch->started_at ?: '—','Completed at'=>$batch->completed_at ?: '—'] as $label=>$value)<div><dt class="ci-muted font-bold">{{ $label }}</dt><dd class="mt-1 break-words">{{ $value }}</dd></div>@endforeach</dl>
    @if($batch->error_summary)<div class="ci-alert-danger mt-5" role="alert">{{ $batch->error_summary }}</div>@endif
    @if($batch->status===\App\Enums\ImportBatchStatus::Queued && $batch->updated_at->lt(now()->subMinutes(5)))<div class="ci-alert-warning mt-5" role="status">This import is queued but has not started. Confirm that a queue worker is running.</div>@endif
    <div class="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">@foreach(['Total'=>$batch->total_rows,'Successful'=>$batch->successful_rows,'Created'=>$batch->created_rows,'Updated'=>$batch->updated_rows,'Skipped'=>$batch->skipped_rows,'Failed'=>$batch->failed_rows] as $label=>$value)<div class="ci-card p-4"><p class="ci-muted text-xs font-bold uppercase">{{ $label }}</p><p class="mt-1 text-2xl font-extrabold">{{ $value }}</p></div>@endforeach</div>
    @if($batch->preview_rows)
        <h3 class="mt-8 text-xl font-extrabold">Preview</h3>
        <div class="ci-table-container mt-3" tabindex="0" aria-label="Scrollable import preview"><table class="min-w-full text-xs"><thead><tr>@foreach($batch->detected_columns as $column)<th scope="col" class="whitespace-nowrap p-3 text-left">{{ $column }}</th>@endforeach</tr></thead><tbody>@foreach($batch->preview_rows as $preview)<tr class="border-t">@foreach($batch->detected_columns as $column)<td class="max-w-xs truncate p-3">{{ $preview[$column] ?? '' }}</td>@endforeach</tr>@endforeach</tbody></table></div>
    @endif
    @if($rows->count() || $batch->completed_at)
        <div class="mt-8 flex flex-wrap items-center justify-between gap-3"><h3 class="text-xl font-extrabold">Row results</h3>@if($batch->failed_rows)<a href="{{ route('superadmin.creator-intelligence.imports.failed-rows',$batch) }}" class="font-bold text-rose-700 dark:text-rose-300">Download failed rows CSV</a>@endif</div>
        <div class="ci-table-container mt-3" tabindex="0" aria-label="Scrollable import row results"><table class="min-w-full text-sm"><thead><tr><th scope="col" class="p-3 text-left">Row</th><th scope="col" class="p-3 text-left">Status</th><th scope="col" class="p-3 text-left">Title</th><th scope="col" class="p-3 text-left">Message</th></tr></thead><tbody>@foreach($rows as $row)<tr class="border-t"><td class="p-3">{{ $row->row_number }}</td><td class="p-3">{{ $row->status->value }}</td><td class="p-3">{{ $row->normalized_data['title'] ?? collect($row->raw_data)->first() }}</td><td class="p-3">{{ $row->message }}</td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $rows->links() }}</div>
    @endif
</x-creator-intelligence-layout>
