@php
    $notificationUser = auth()->user();
    $notificationUnreadCount = $notificationUser->unreadNotifications()->count();
    $notificationItems = $notificationUser->notifications()->latest()->limit(10)->get()->map(fn ($item) => new \App\Presenters\NotificationPresenter($item));
@endphp
<div data-header-notification-control class="relative flex shrink-0 items-center" @click.outside="notificationsOpen = false">
    <button type="button" @click="toggleNotifications()" :aria-expanded="notificationsOpen.toString()" aria-controls="notification-dropdown" aria-label="Notifications{{ $notificationUnreadCount ? ', '.$notificationUnreadCount.' unread' : '' }}" data-header-circle-trigger="notifications" class="relative inline-flex size-11 shrink-0 items-center justify-center rounded-full border border-slate-200 bg-white leading-none text-slate-600 shadow-sm transition hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-600 focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300 dark:hover:border-indigo-500 dark:hover:bg-slate-800 dark:focus-visible:ring-offset-slate-950">
        <svg data-notification-bell-icon class="block size-5 shrink-0" viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 7h18s-3 0-3-7M10 20h4"/></svg>
        @if($notificationUnreadCount)<span data-notification-unread-badge class="absolute -right-1 -top-1 inline-flex min-h-5 min-w-5 items-center justify-center rounded-full bg-red-600 px-1 text-[10px] font-black text-white"><span class="sr-only">{{ $notificationUnreadCount }} unread notifications</span><span aria-hidden="true">{{ $notificationUnreadCount > 99 ? '99+' : $notificationUnreadCount }}</span></span>@endif
    </button>
    <div id="notification-dropdown" data-notification-panel role="region" aria-labelledby="notification-dropdown-title" x-show="notificationsOpen" x-cloak x-transition.origin.top.right class="fixed inset-x-3 top-[4.5rem] z-50 max-h-[calc(100dvh-5.25rem)] overflow-y-auto overscroll-contain rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-800 dark:bg-slate-900 sm:absolute sm:inset-x-auto sm:right-0 sm:top-full sm:mt-2 sm:w-96 sm:max-w-[calc(100vw-2rem)] sm:max-h-[min(70vh,35rem)]">
        <div class="flex items-center justify-between border-b border-slate-200 p-4 dark:border-slate-800"><div><h2 id="notification-dropdown-title" class="font-extrabold">Notifications</h2><p class="text-xs text-slate-500">{{ $notificationUnreadCount }} unread</p></div>@if($notificationUnreadCount)<form method="POST" action="{{ route('notifications.read-all') }}">@csrf<button class="text-sm font-bold text-indigo-600 dark:text-indigo-300">Mark all read</button></form>@endif</div>
        @forelse($notificationItems as $item)<a href="{{ route('notifications.open', $item->id()) }}" class="block border-b border-slate-100 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800"><x-notifications.item :item="$item" compact /></a>@empty<div class="p-8 text-center"><p class="font-bold">You’re all caught up.</p><p class="mt-1 text-sm text-slate-500">New updates will appear here.</p></div>@endforelse
        <a href="{{ route('notifications.index') }}" class="block p-4 text-center text-sm font-bold text-indigo-600 dark:text-indigo-300">View all notifications</a>
    </div>
</div>
