<x-super-admin-layout title="Assist Creator Setup">
    @php($owner = $creator->creatorOwners->first()?->user)
    <nav aria-label="Creator assistance" class="mb-6 flex flex-wrap gap-2"><a href="{{ route('super-admin.creators.assist',$creator) }}" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Setup</a><a href="{{ route('super-admin.creators.requests.index',$creator) }}" class="rounded-xl border border-slate-300 px-4 py-2 font-bold">Requests</a><a href="#admin-history" class="rounded-xl border border-slate-300 px-4 py-2 font-bold">Audit History</a></nav>
    <div class="mb-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-950 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-100">
        <div class="font-extrabold">Super Admin Assistance Mode</div>
        <p class="mt-1">You are editing {{ $creator->display_name }}’s public creator space. All changes are recorded.</p>
    </div>
    <div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
        <div class="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900">
            <div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h2 class="text-2xl font-extrabold">Assist Creator Setup</h2><p class="text-slate-500">Owner: {{ $owner?->public_display_name ?: $owner?->name ?: 'Unknown' }} ({{ $owner?->email ?: 'no email' }})</p><p class="text-sm text-slate-500">Ownership and Google identity cannot be changed here.</p></div><div class="text-right"><div class="text-2xl font-extrabold text-indigo-600">{{ $setup['percentage'] }}%</div><div class="text-xs text-slate-500">setup complete</div></div></div>
            @if($errors->any())<div class="mb-5 rounded-xl bg-red-50 p-4 text-red-700">Please correct the highlighted fields.</div>@endif
            <form method="POST" action="{{ route('super-admin.creators.update', $creator) }}" enctype="multipart/form-data" class="space-y-5">@csrf @method('PUT')
                <div><x-input-label for="display_name" value="Public creator name"/><x-text-input id="display_name" name="display_name" class="mt-1 block w-full" :value="old('display_name',$creator->display_name)" required/><x-input-error :messages="$errors->get('display_name')" class="mt-2"/></div>
                <div><x-input-label for="slug" value="Public handle / slug"/><x-text-input id="slug" name="slug" class="mt-1 block w-full" :value="old('slug',$creator->slug)" required/><x-input-error :messages="$errors->get('slug')" class="mt-2"/></div>
                <div><x-input-label for="youtube_channel_url" value="YouTube channel URL"/><x-text-input id="youtube_channel_url" name="youtube_channel_url" type="url" class="mt-1 block w-full" :value="old('youtube_channel_url',$creator->youtube_channel_url ?: $creator->channel_url)"/><x-input-error :messages="$errors->get('youtube_channel_url')" class="mt-2"/></div>
                <div><x-input-label for="bio" value="Biography"/><textarea id="bio" name="bio" rows="5" maxlength="2000" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('bio',$creator->bio) }}</textarea><x-input-error :messages="$errors->get('bio')" class="mt-2"/></div>
                <div><x-input-label for="tags" value="Creator tags (comma separated)"/><x-text-input id="tags" name="tags" class="mt-1 block w-full" :value="old('tags',$creator->creatorTags->pluck('name')->implode(', '))"/><p class="mt-1 text-xs text-slate-500">Tags already used by requests are retained to preserve history.</p><x-input-error :messages="$errors->get('tags')" class="mt-2"/></div>
                <div><x-input-label for="submission_instructions" value="Request instructions"/><textarea id="submission_instructions" name="submission_instructions" rows="4" maxlength="2000" class="mt-1 block w-full rounded-md border-slate-300 dark:border-slate-700 dark:bg-slate-950">{{ old('submission_instructions',$creator->submission_instructions) }}</textarea></div>
                <div class="grid gap-5 md:grid-cols-2"><div><x-input-label for="avatar" value="Avatar (JPG, PNG, WebP; max 2MB)"/>@if($creator->avatar_url)<img src="{{ $creator->avatar_url }}" class="my-2 size-24 rounded-full object-cover" alt="Current avatar">@endif<input id="avatar" name="avatar" type="file" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full text-sm"><label class="mt-2 block text-sm"><input type="checkbox" name="remove_avatar" value="1"> Remove current avatar</label></div>
                <div><x-input-label for="hero" value="Banner (JPG, PNG, WebP; max 5MB)"/>@if($creator->hero_url)<img src="{{ $creator->hero_url }}" class="my-2 h-24 w-full rounded-xl object-cover" alt="Current banner">@endif<input id="hero" name="hero" type="file" accept="image/jpeg,image/png,image/webp" class="mt-2 block w-full text-sm"><label class="mt-2 block text-sm"><input type="checkbox" name="remove_hero" value="1"> Remove current banner</label></div></div>
                <label class="flex items-center gap-2"><input type="hidden" name="submissions_open" value="0"><input type="checkbox" name="submissions_open" value="1" @checked(old('submissions_open',$creator->submissions_open))> Accept new requests</label>
                <fieldset><legend class="font-bold">Request moderation</legend><label class="mr-5"><input type="radio" name="recommendation_approval_mode" value="manual" @checked(old('recommendation_approval_mode',$creator->recommendation_approval_mode)==='manual')> Review before publishing</label><label><input type="radio" name="recommendation_approval_mode" value="auto" @checked(old('recommendation_approval_mode',$creator->recommendation_approval_mode)==='auto')> Appear immediately</label></fieldset>
                <div class="flex flex-wrap gap-3"><button name="save_action" value="save" class="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white">Save changes</button><button name="save_action" value="preview" class="rounded-xl border border-indigo-300 px-5 py-3 font-bold text-indigo-700 dark:text-indigo-300">Save and preview</button><a href="{{ route('super-admin.creators.preview',$creator) }}" class="px-4 py-3 font-bold text-indigo-600">Preview current page</a></div>
            </form>
        </div>
        <aside class="space-y-6">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-extrabold">Setup checklist</h3>@if($setup['missing'])<ul class="mt-3 list-disc space-y-1 pl-5 text-sm">@foreach($setup['missing'] as $item)<li>{{ $item }}</li>@endforeach</ul>@else<p class="mt-2 text-sm text-emerald-600">All required setup items are complete.</p>@endif</section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-extrabold">Add starter requests</h3><p class="mt-1 text-sm text-slate-500">Added as creator-origin content and attributed to the creator owner, not the Super Admin Guide.</p><form method="POST" action="{{ route('super-admin.creators.starter',$creator) }}" class="mt-4 space-y-3">@csrf<input name="suggestions[0][title]" placeholder="Request title" class="w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><input name="suggestions[0][url]" type="url" placeholder="Optional link" class="w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><select name="suggestions[0][category]" class="w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"><option value="">No category</option>@foreach($categories as $category)<option value="{{ $category }}">{{ ucfirst($category) }}</option>@endforeach</select><textarea name="suggestions[0][note]" placeholder="Optional context" class="w-full rounded-lg border-slate-300 dark:border-slate-700 dark:bg-slate-950"></textarea><button class="rounded-lg bg-indigo-600 px-4 py-2 font-bold text-white">Add starter request</button></form></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-extrabold">Recent admin activity</h3><div class="mt-3 space-y-3 text-sm">@forelse($history as $entry)<div><div class="font-semibold">{{ $entry->description }}</div><div class="text-xs text-slate-500">{{ $entry->created_at->format('M j, Y g:i A') }} by {{ $entry->admin?->name ?: 'Former admin' }}</div></div>@empty<p class="text-slate-500">No administrative changes recorded yet.</p>@endforelse</div></section>
        </aside>
    </div>
</x-super-admin-layout>
