<x-super-admin-layout title="Announcements">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-2xl font-extrabold">Announcements</h2><p class="mt-1 text-sm text-slate-500">Draft, schedule, and monitor in-app announcements.</p></div><a href="{{ route('super-admin.announcements.create') }}" class="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white">Create announcement</a></div>
    <div class="overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">
        <table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-slate-950"><tr><th class="p-4">Announcement</th><th class="p-4">Audience</th><th class="p-4">Status / schedule</th><th class="p-4">Delivery</th><th class="p-4">Created by</th><th class="p-4">Actions</th></tr></thead>
        <tbody class="divide-y divide-slate-200 dark:divide-slate-800">
            @forelse($announcements as $announcement)
                <tr class="align-top"><td class="p-4"><p class="font-extrabold">{{ $announcement->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $announcement->internal_name }}</p></td><td class="p-4">{{ $announcement->audienceLabel() }}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{{ $announcement->statusLabel() }}</span><p class="mt-2 text-xs text-slate-500">{{ $announcement->starts_at?->format('M j, Y g:i A') ?: 'No schedule' }}</p>@if($announcement->published_at)<p class="text-xs text-slate-500">Published {{ $announcement->published_at->format('M j, Y g:i A') }}</p>@endif</td><td class="p-4"><p class="font-bold">{{ number_format($announcement->delivered_count) }} / {{ number_format($announcement->recipient_count) }}</p>@if($announcement->failed_count)<p class="text-xs font-bold text-red-600">{{ number_format($announcement->failed_count) }} failed</p>@else<p class="text-xs text-slate-500">No failures</p>@endif</td><td class="p-4">{{ $announcement->creator?->publicName() ?: 'System' }}</td>
                    <td class="p-4"><div class="flex flex-wrap gap-3">@if($announcement->isEditable())<a href="{{ route('super-admin.announcements.edit', $announcement) }}" class="font-bold text-indigo-600">Edit / Preview</a><form method="POST" action="{{ route('super-admin.announcements.publish', $announcement) }}">@csrf<button class="font-bold text-emerald-600">Publish now</button></form><form method="POST" action="{{ route('super-admin.announcements.cancel', $announcement) }}">@csrf<button class="font-bold text-amber-600">Cancel</button></form>@endif<form method="POST" action="{{ route('super-admin.announcements.duplicate', $announcement) }}">@csrf<button class="font-bold text-indigo-600">Duplicate</button></form>@if($announcement->isEditable())<form method="POST" action="{{ route('super-admin.announcements.destroy', $announcement) }}" onsubmit="return confirm('Delete this announcement?')">@csrf @method('DELETE')<button class="font-bold text-red-600">Delete</button></form>@endif</div></td></tr>
            @empty<tr><td colspan="6" class="p-10 text-center text-slate-500">No announcements yet.</td></tr>@endforelse
        </tbody></table>
    </div>
    <div class="mt-5">{{ $announcements->links() }}</div>
</x-super-admin-layout>
