<?php

return [
    'public_enabled' => (bool) env('DAILY_JOURNEY_PUBLIC_ENABLED', false),
    'key' => env('DAILY_JOURNEY_KEY', 'daily-journey'),
    'title' => env('DAILY_JOURNEY_TITLE', 'Daily Journey Challenge'),
    'timezone' => env('DAILY_JOURNEY_TIMEZONE', 'Asia/Manila'),
    'version' => 'daily-journey-v1',
    'supported_versions' => ['daily-journey-v1'],
    'grace_minutes' => 5,
    'session_minutes' => 30,
    'maximum_run_minutes' => 20,
    'collectible_bonus' => 25,
    'starting_speed' => 340,
    'maximum_speed' => 720,
    'acceleration_per_second' => 7,
    'minimum_obstacle_gap' => 390,
    'maximum_obstacle_gap' => 680,
    'leaderboard_size' => 25,
    'cache_seconds' => 30,
    'all_time_enabled' => false,
    'accolade_track' => 'guide_daily_challenge_wins',
    'ui' => [
        'countdown_step_ms' => 700,
        'toast_duration_ms' => 1400,
        'toast_queue_limit' => 3,
        'hud_update_ms' => 100,
        'shield_broken_ms' => 900,
        'score_milestones' => [1000, 2500, 5000, 10000],
        'reset_warning_minutes' => [10, 1],
        'overlay_max_width' => 580,
    ],
];
