<x-creator-intelligence-layout :title="$subject->exists ? 'Edit '.$labels->subject : 'Add '.$labels->subject">
    <h2 class="mb-5 text-2xl font-extrabold">{{ $subject->exists ? 'Edit '.$labels->subject : 'Add '.$labels->subject }}</h2>
    <form method="POST" action="{{ $subject->exists ? route('superadmin.creator-intelligence.subjects.update', $subject) : route('superadmin.creator-intelligence.subjects.store') }}" class="ci-form-card max-w-2xl space-y-5">@csrf @if($subject->exists) @method('PUT') @endif
        <div><label for="subject-channel" class="ci-label">Creator Channel</label><select id="subject-channel" name="creator_channel_id" required class="ci-control mt-1 block w-full">@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected(old('creator_channel_id', $subject->creator_channel_id) == $channel->id)>{{ $channel->channel_name }} · {{ $channel->subject_label }}</option>@endforeach</select></div>
        <div><label for="subject-name" class="ci-label">{{ $labels->subject }} Name</label><input id="subject-name" name="name" required maxlength="150" value="{{ old('name', $subject->name) }}" aria-describedby="subject-name-help @error('name') subject-name-error @enderror" @error('name') aria-invalid="true" @enderror class="ci-control mt-1 block w-full @error('name') !border-rose-500 @enderror"><p id="subject-name-help" class="ci-help mt-1">Capitalization is preserved exactly as entered after surrounding and repeated whitespace is cleaned.</p>@error('name')<p id="subject-name-error" class="ci-error">{{ $message }}</p>@enderror</div>
        <div><label for="subject-type" class="ci-label">{{ $labels->subject }} Type</label><input id="subject-type" name="subject_type" maxlength="100" value="{{ old('subject_type', $subject->subject_type) }}" class="ci-control mt-1 block w-full"></div>
        <div><label for="subject-country" class="ci-label">Country Code</label><input id="subject-country" name="country_code" maxlength="2" value="{{ old('country_code', $subject->country_code) }}" aria-describedby="subject-country-help" class="ci-control mt-1 block w-full uppercase"><p id="subject-country-help" class="ci-help mt-1">Optional two-letter country code.</p></div>
        <div><label for="subject-notes" class="ci-label">Notes</label><textarea id="subject-notes" name="notes" rows="4" class="ci-control mt-1 block w-full">{{ old('notes', $subject->notes) }}</textarea></div>
        <label class="flex items-center gap-3 font-bold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $subject->is_active ?? true))> Active {{ $labels->subject }}</label>
        <button class="ci-button-primary">Save {{ $labels->subject }}</button>
    </form>
</x-creator-intelligence-layout>
