<x-creator-intelligence-layout :title="str($report)->headline().' Analytics'">
    @php
        $tabs = ['channel'=>'Channel Performance','subjects'=>($context->channel?->subject_label ?? 'Subject').' Performance','content-items'=>($context->channel?->content_item_label ?? 'Content Item').' Performance','timing'=>'Upload Timing','titles'=>'Titles','thumbnails'=>'Thumbnails','editorial'=>'Editorial','hype'=>'Hype'];
        $fmt = fn($value, $decimals = 0) => $value === null ? 'No data' : number_format((float) $value, $decimals);
        $currency = $context->channel?->profile?->default_currency ?? 'USD';
        $dimensions = [
            'timing'=>['weekday'=>'Day of Week','hour'=>'Hour of Day','day_hour'=>'Day and Hour','daypart'=>'Daypart','month'=>'Month'],
            'titles'=>['title_contains_question'=>'Contains Question','title_contains_exclamation'=>'Contains Exclamation','title_contains_pipe'=>'Contains Pipe','title_contains_parentheses'=>'Contains Parentheses','title_contains_all_caps'=>'Contains All Caps','subject_name_present'=>'Subject Name Present','content_item_name_present'=>'Content Item Name Present','negative_hook'=>'Negative Hook','curiosity_hook'=>'Curiosity Hook','emotional_hook'=>'Emotional Hook','controversy_hook'=>'Controversy Hook','technical_hook'=>'Technical Hook','discovery_hook'=>'Discovery Hook','title_template'=>'Title Template','title_character_count'=>'Character Count Bucket','title_word_count'=>'Word Count Bucket'],
            'thumbnails'=>['creator_expression'=>'Creator Expression','background_style'=>'Background Style','dominant_color_label'=>'Dominant Color','layout_style'=>'Layout Style','text_position'=>'Text Position','thumbnail_text_word_count'=>'Text Word Count Bucket','face_count'=>'Face Count Bucket','creator_face_visible'=>'Creator Face Visible','subject_face_visible'=>'Subject Face Visible','thumbnail_contains_question'=>'Contains Question','contains_arrow'=>'Contains Arrow','contains_circle'=>'Contains Circle','contains_flag'=>'Contains Flag','contains_logo'=>'Contains Logo'],
            'editorial'=>['creator_sentiment'=>'Creator Sentiment','reaction_style'=>'Reaction Style','energy_level'=>'Energy Level','technical_depth'=>'Technical Depth','humor_level'=>'Humor Level','cultural_context_level'=>'Cultural Context'],
            'hype'=>['videos'=>'Videos','subjects'=>($context->channel?->subject_label ?? 'Subject').'s'],
        ];
    @endphp
    <nav aria-label="Analytics reports" class="mb-6 flex flex-wrap gap-2">@foreach($tabs as $key=>$label)<a class="rounded-xl px-3 py-2 text-sm font-bold {{ $report===$key?'bg-indigo-600 text-white':'border bg-white dark:bg-slate-900' }}" href="{{ route('superadmin.creator-intelligence.analytics.report', ['report'=>$key] + request()->except('dimension')) }}">{{ $label }}</a>@endforeach</nav>

    <form method="GET" class="rounded-2xl border bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
        <div class="grid gap-4 md:grid-cols-3 xl:grid-cols-5">
            <label class="text-sm font-bold">Creator Profile<select name="creator_profile_id" class="mt-1 block w-full rounded-xl"><option value="">All profiles</option>@foreach($profiles as $profile)<option value="{{ $profile->id }}" @selected(request('creator_profile_id')==$profile->id)>{{ $profile->display_name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Creator Channel<select name="creator_channel_id" class="mt-1 block w-full rounded-xl"><option value="">First active channel</option>@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected($context->channel?->id==$channel->id)>{{ $channel->channel_name }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Published From<input type="date" name="published_from" value="{{ request('published_from') }}" class="mt-1 block w-full rounded-xl"></label><label class="text-sm font-bold">Published To<input type="date" name="published_to" value="{{ request('published_to') }}" class="mt-1 block w-full rounded-xl"></label>
            <label class="text-sm font-bold">Snapshot Source<select name="snapshot_source" class="mt-1 block w-full rounded-xl"><option value="">Resolved latest</option>@foreach($sources as $source)<option value="{{ $source->value }}" @selected(request('snapshot_source')===$source->value)>{{ str($source->value)->headline() }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Snapshot From<input type="date" name="snapshot_from" value="{{ request('snapshot_from') }}" class="mt-1 block w-full rounded-xl"></label><label class="text-sm font-bold">Snapshot To<input type="date" name="snapshot_to" value="{{ request('snapshot_to') }}" class="mt-1 block w-full rounded-xl"></label>
            <label class="text-sm font-bold">Video Format<select name="video_format" class="mt-1 block w-full rounded-xl"><option value="">All</option>@foreach($formats as $option)<option value="{{ $option->value }}" @selected(request('video_format')===$option->value)>{{ str($option->value)->headline() }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Content Type<select name="content_type" class="mt-1 block w-full rounded-xl"><option value="">All</option>@foreach($types as $option)<option value="{{ $option->value }}" @selected(request('content_type')===$option->value)>{{ str($option->value)->headline() }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Copyright<select name="copyright_status" class="mt-1 block w-full rounded-xl"><option value="">All</option>@foreach($copyrights as $option)<option value="{{ $option->value }}" @selected(request('copyright_status')===$option->value)>{{ str($option->value)->headline() }}</option>@endforeach</select></label>
            <label class="text-sm font-bold">Monetization<select name="monetization_status" class="mt-1 block w-full rounded-xl"><option value="">All</option><option value="1" @selected(request('monetization_status')==='1')>Monetized</option><option value="0" @selected(request('monetization_status')==='0')>Not monetized</option><option value="unknown" @selected(request('monetization_status')==='unknown')>Unknown</option></select></label>
            <label class="text-sm font-bold">Minimum Completion<input type="number" min="0" max="100" name="minimum_metadata_completion" value="{{ request('minimum_metadata_completion',0) }}" class="mt-1 block w-full rounded-xl"></label><label class="text-sm font-bold">Minimum Sample<input type="number" min="1" max="1000" name="minimum_sample_size" value="{{ $context->sampleMinimum() }}" class="mt-1 block w-full rounded-xl"></label>
            @if(isset($dimensions[$report]))<label class="text-sm font-bold">Analysis Dimension<select name="dimension" class="mt-1 block w-full rounded-xl">@foreach($dimensions[$report] as $key=>$label)<option value="{{ $key }}" @selected(request('dimension')===$key)>{{ $label }}</option>@endforeach</select></label>@endif
        </div>
        <div class="mt-4 flex flex-wrap gap-5 text-sm">@foreach(['include_shorts'=>'Include Shorts','include_lives'=>'Include Lives','include_without_performance'=>'Include Videos Without Performance','show_low_sample'=>'Show Groups Below Minimum'] as $field=>$label)<input type="hidden" name="{{ $field }}" value="0"><label><input type="checkbox" name="{{ $field }}" value="1" @checked($context->filters[$field])> {{ $label }}</label>@endforeach @if(in_array($report,['titles','thumbnails','editorial']))<label><input type="checkbox" name="include_unreviewed" value="1" @checked($context->filters['include_unreviewed'])> Include unreviewed metadata</label>@endif @if($report==='subjects')<label><input type="checkbox" name="include_secondary" value="1" @checked($context->filters['include_secondary'])> Include featured and secondary relationships</label>@endif</div>
        <div class="mt-5 flex gap-3"><button class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white">Apply Filters</button><a href="{{ route('superadmin.creator-intelligence.analytics.report',$report) }}" class="rounded-xl border px-4 py-2 font-bold">Clear Filters</a><a href="{{ route('superadmin.creator-intelligence.analytics.export', ['report'=>$report] + request()->query()) }}" class="rounded-xl border px-4 py-2 font-bold">Export CSV</a></div>
    </form>

    <div class="mt-5 rounded-xl bg-slate-100 p-4 text-sm dark:bg-slate-900"><strong>Performance basis:</strong> {{ request('snapshot_source') ? 'Latest qualifying '.str(request('snapshot_source'))->headline().' snapshot per video' : 'Latest available snapshot per video' }}. <strong>Source priority:</strong> {{ collect($sourcePriority)->map(fn($source)=>str($source)->headline())->join(' → ') }}. @if($report==='timing')<strong>Timezone:</strong> {{ $context->channel?->default_publish_timezone ?? 'UTC' }}. Timing correlation may reflect content selection rather than timing itself.@endif @if($report==='editorial') Sentiment and reaction labels are editorial classifications and must not be interpreted as the creator's authentic internal state.@endif</div>

    <section class="mt-6" aria-labelledby="coverage-title"><h2 id="coverage-title" class="text-xl font-extrabold">Data coverage</h2><dl class="mt-3 grid gap-3 sm:grid-cols-3 lg:grid-cols-5">@foreach(['videos'=>'Filtered videos','views'=>'With views','ctr'=>'With CTR','hype_reported'=>'Hype data reported','hype_positive'=>'Videos receiving Hype','reviewed_titles'=>'Reviewed titles','reviewed_thumbnails'=>'Reviewed thumbnails','reviewed_editorial'=>'Reviewed editorial'] as $key=>$label)<div class="rounded-xl border bg-white p-3 dark:bg-slate-900"><dt class="text-xs font-bold text-slate-500">{{ $label }}</dt><dd class="text-xl font-black">{{ $data['coverage'][$key] }}</dd></div>@endforeach<div class="rounded-xl border bg-white p-3 dark:bg-slate-900"><dt class="text-xs font-bold text-slate-500">Percentage receiving Hype</dt><dd class="text-xl font-black">{{ $data['coverage']['hype_receiving_percentage'] === null ? 'No data' : $fmt($data['coverage']['hype_receiving_percentage'], 1).'%' }}</dd><dd class="mt-1 text-xs text-slate-500">Of videos with reported Hype data</dd></div></dl></section>

    @if($report==='channel')<section class="mt-6"><h2 class="text-xl font-extrabold">Channel summary</h2><div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['views','impressions_ctr','watch_time_minutes','average_percentage_viewed','subscribers_gained','estimated_revenue','hype_points','metadata_completion_percentage'] as $metric)@php($summaryRows=$metricRegistry->summaryRows($metric, $data['summary'][$metric], $data['metadata_status_counts'], $currency))@php($summaryNote=$metricRegistry->summaryNote($metric, $data['summary'][$metric], $data['coverage']))<div class="min-w-0 overflow-hidden rounded-xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><h3 class="font-bold">{{ $metricRegistry->label($metric) }}</h3><dl class="mt-2 space-y-1">@foreach($summaryRows as $summaryRow)<div class="grid grid-cols-[minmax(0,1fr)_auto] items-baseline gap-3"><dt class="min-w-0">{{ $summaryRow['label'] }}</dt><dd class="whitespace-nowrap font-bold" @if($summaryRow['title']) title="{{ $summaryRow['title'] }}" @endif>{{ $summaryRow['value'] }}</dd></div>@endforeach</dl>@if($summaryNote)<p class="mt-3 rounded-lg bg-slate-100 p-2 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ $summaryNote }}</p>@endif</div>@endforeach</div></section>@endif

    @if($report==='subjects')<form method="GET" class="mt-6 rounded-xl border p-4"><input type="hidden" name="creator_channel_id" value="{{ $context->channel?->id }}"><input type="hidden" name="minimum_sample_size" value="{{ $context->sampleMinimum() }}"><label class="font-bold">Compare <select name="subject_id" class="rounded-xl"><option value="">Select {{ strtolower($context->channel?->subject_label ?? 'subject') }}</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(request('subject_id')==$subject->id)>{{ $subject->name }}</option>@endforeach</select></label><label class="ml-3">against <select name="compare_subject_id" class="rounded-xl"><option value="">All non-selected videos</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(request('compare_subject_id')==$subject->id)>{{ $subject->name }}</option>@endforeach</select></label><button class="ml-3 rounded-xl bg-slate-900 px-4 py-2 text-white">Compare</button></form>@endif
    @if($data['comparison'])<section class="mt-6 rounded-2xl border p-5"><h2 class="font-extrabold">{{ $data['comparison']['left_label'] }} versus {{ $data['comparison']['right_label'] }}</h2><div class="mt-3 overflow-x-auto"><table class="min-w-full"><thead><tr><th class="p-2 text-left">Metric</th><th>Selected</th><th>Comparison</th><th>Absolute difference</th><th>Relative difference</th></tr></thead><tbody>@foreach($data['comparison']['differences'] as $metric=>$difference)<tr class="border-t"><th class="p-2 text-left">Average {{ $metricRegistry->label($metric) }}</th><td class="text-center">{{ $fmt($data['comparison']['left'][$metric]['mean'],2) }} (n={{ $data['comparison']['left'][$metric]['eligible_video_count'] }})</td><td class="text-center">{{ $fmt($data['comparison']['right'][$metric]['mean'],2) }} (n={{ $data['comparison']['right'][$metric]['eligible_video_count'] }})</td><td class="text-center">{{ $fmt($difference['absolute'],2) }}{{ $metric==='impressions_ctr'?' percentage points':'' }}</td><td class="text-center">{{ $difference['relative']===null?'Not available':$fmt($difference['relative'],1).'%' }}</td></tr>@endforeach</tbody></table></div><p class="mt-3 text-sm text-slate-500">Descriptive comparison only; it does not establish causation or statistical significance.</p></section>@endif

    <section class="mt-6">
        <h2 class="text-xl font-extrabold">{{ $tabs[$report] }}</h2>
        @if($data['groups']->isEmpty())
            <div class="mt-3 rounded-xl border border-dashed border-slate-300 bg-white p-8 text-center dark:border-slate-700 dark:bg-slate-900">
                @if($report === 'subjects' && $data['empty_state'] === 'no_relationships')
                    <p class="font-bold">No subjects have been assigned to these videos yet.</p>
                    <p class="mx-auto mt-2 max-w-2xl text-sm text-slate-600 dark:text-slate-300">Assign primary subjects in the Metadata Queue or use bulk actions from the Videos page. Subject analytics will appear once videos are classified.</p>
                    <div class="mt-5 flex flex-wrap justify-center gap-3">
                        <a href="{{ route('superadmin.creator-intelligence.metadata-queue.index', array_filter(['creator_channel_id'=>$context->channel?->id, 'missing_subject'=>1])) }}" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-slate-900">Open Metadata Queue</a>
                        <a href="{{ route('superadmin.creator-intelligence.subjects.index', array_filter(['creator_channel_id'=>$context->channel?->id])) }}" class="rounded-xl border border-slate-300 px-4 py-2 font-bold outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700">Manage Subjects</a>
                        <a href="{{ route('superadmin.creator-intelligence.videos.index', array_filter(['creator_channel_id'=>$context->channel?->id])) }}" class="rounded-xl border border-slate-300 px-4 py-2 font-bold outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700">Browse Videos</a>
                    </div>
                @elseif($report === 'subjects' && $data['empty_state'] === 'below_minimum')
                    <p class="font-bold">No subjects meet the current minimum sample size of {{ $context->sampleMinimum() }} videos.</p>
                    <div class="mt-5 flex flex-wrap justify-center gap-3">
                        <a href="{{ route('superadmin.creator-intelligence.analytics.report', array_merge(['report'=>$report], request()->query(), ['show_low_sample'=>1])) }}" class="rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-slate-900">Show Low-Sample Groups</a>
                        <a href="{{ route('superadmin.creator-intelligence.analytics.report', array_merge(['report'=>$report], request()->query(), ['minimum_sample_size'=>1])) }}" class="rounded-xl border border-slate-300 px-4 py-2 font-bold outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700">Lower Minimum Sample</a>
                    </div>
                @elseif($report === 'subjects' && $data['empty_state'] === 'no_videos')
                    <p class="font-bold">No videos match the current analytics filters.</p>
                    <div class="mt-5"><a href="{{ route('superadmin.creator-intelligence.analytics.report', $report) }}" class="inline-flex rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-slate-900">Clear Filters</a></div>
                @elseif($report === 'subjects' && $data['empty_state'] === 'no_primary_relationships')
                    <p class="font-bold">No primary subjects are assigned in the current dataset.</p>
                    <p class="mx-auto mt-2 max-w-2xl text-sm text-slate-600 dark:text-slate-300">Assign primary subjects or enable Include featured and secondary relationships.</p>
                    <div class="mt-5"><a href="{{ route('superadmin.creator-intelligence.analytics.report', array_merge(['report'=>$report], request()->query(), ['include_secondary'=>1])) }}" class="inline-flex rounded-xl bg-indigo-600 px-4 py-2 font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-slate-900">Include Secondary Relationships</a></div>
                @else
                    <p class="font-bold">No groups meet the current filters and minimum sample size.</p>
                    <p class="mt-2 text-sm text-slate-600 dark:text-slate-300">Show low-sample groups, lower the minimum sample, import performance data, classify metadata, or clear filters.</p>
                @endif
            </div>
        @else
            <div class="mt-3 max-w-full overflow-x-auto rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900" tabindex="0" aria-label="Scrollable channel performance table">
                <table class="min-w-[1280px] border-separate border-spacing-0 text-sm">
                    <thead class="sticky top-0 z-20 bg-slate-100 text-slate-700 dark:bg-slate-950 dark:text-slate-200">
                        <tr>
                            <th scope="col" class="sticky left-0 z-30 min-w-56 bg-slate-100 px-4 py-3 text-left font-bold dark:bg-slate-950">Group</th>
                            @foreach(['Videos','Average Views','Median Views','Average CTR','Subscribers','Revenue','Average Hype','Consistency'] as $heading)
                                <th scope="col" class="min-w-28 px-4 py-3 text-right font-bold leading-tight whitespace-normal">{{ $heading }}</th>
                            @endforeach
                            <th scope="col" class="min-w-72 px-4 py-3 text-left font-bold">Top Video</th>
                            <th scope="col" class="min-w-32 px-4 py-3 text-right font-bold leading-tight whitespace-normal">Sample Strength</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-slate-200 dark:divide-slate-800">
                        @foreach($data['groups'] as $group)
                            <tr>
                                <th scope="row" class="sticky left-0 z-10 min-w-56 bg-white px-4 py-3 text-left align-top font-bold dark:bg-slate-900">
                                    <span class="break-words">{{ $group['label'] }}</span>
                                    <details class="mt-2 rounded-lg font-normal open:bg-slate-50 open:p-2 dark:open:bg-slate-800">
                                        <summary class="cursor-pointer rounded text-xs font-bold text-indigo-600 outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 dark:text-indigo-300 dark:focus-visible:ring-offset-slate-900">Optional metrics</summary>
                                        <dl class="mt-2 grid grid-cols-[minmax(0,1fr)_auto] gap-x-3 gap-y-1 text-xs text-slate-600 dark:text-slate-300">
                                            <dt>Min–max views</dt><dd class="text-right">{{ $metricRegistry->formatValue('views', $group['metrics']['views']['minimum']) }}–{{ $metricRegistry->formatValue('views', $group['metrics']['views']['maximum']) }}</dd>
                                            <dt>Median CTR</dt><dd class="text-right">{{ $metricRegistry->formatValue('impressions_ctr', $group['metrics']['impressions_ctr']['median']) }}</dd>
                                            <dt>Total Hype</dt><dd class="text-right">{{ $metricRegistry->formatValue('hype_points', $group['metrics']['hype_points']['sum'], 'total') }}</dd>
                                            <dt>Top share</dt><dd class="text-right">{{ $group['top_video_share']===null?'N/A':$fmt($group['top_video_share'],1).'%' }}</dd>
                                        </dl>
                                    </details>
                                </th>
                                <td class="px-4 py-3 text-right tabular-nums">{{ number_format($group['video_count']) }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('views', $group['metrics']['views']['mean'], 'mean') }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('views', $group['metrics']['views']['median'], 'median') }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('impressions_ctr', $group['metrics']['impressions_ctr']['mean'], 'mean') }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('subscribers_gained', $group['metrics']['subscribers_gained']['sum'], 'total') }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('estimated_revenue', $group['metrics']['estimated_revenue']['sum'], 'total', $currency) }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('hype_points', $group['metrics']['hype_points']['mean'], 'mean') }}</td>
                                <td class="px-4 py-3 text-right tabular-nums">{{ $metricRegistry->formatValue('consistency_score', $group['metrics']['views']['consistency_score'], 'mean') }}</td>
                                <td class="min-w-72 max-w-80 px-4 py-3 text-left">@if($group['top_video'])<a class="line-clamp-2 break-words font-bold text-indigo-600 outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-indigo-300" title="{{ $group['top_video']->title }}" href="{{ route('superadmin.creator-intelligence.videos.show',$group['top_video']) }}">{{ $group['top_video']->title }}</a>@else No views data @endif @if(($group['top_video_share']??0)>=50)<span class="mt-1 block text-xs font-bold text-amber-700 dark:text-amber-300">Outlier-sensitive</span>@endif</td>
                                <td class="px-4 py-3 text-right"><span class="inline-flex whitespace-nowrap rounded-full border border-slate-300 px-2 py-1 text-xs font-bold dark:border-slate-700">{{ $group['sample_strength'] }}</span></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <p class="mt-3 text-sm text-slate-500">Missing metric values are excluded, while explicit zeroes are included. Experimental Consistency Score = max(0, 100 − coefficient of variation × 100), available only for at least three eligible videos with a positive mean. Group overlap is possible when secondary relationships are included.</p>
        @endif
    </section>
</x-creator-intelligence-layout>
