@php($ad = $advertisement ?? null)
@if ($errors->any())<div class="mb-6 rounded-xl bg-red-50 p-4 text-red-800"><p class="font-bold">Please correct the highlighted fields.</p><ul class="mt-2 list-disc pl-5 text-sm">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-6 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900 lg:grid-cols-2">
    <div><label for="internal_name" class="font-bold">Internal name</label><input id="internal_name" name="internal_name" required value="{{ old('internal_name', $ad?->internal_name) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"><x-input-error :messages="$errors->get('internal_name')" class="mt-2" /></div>
    <div><label for="advertiser_name" class="font-bold">Advertiser name <span class="font-normal text-slate-500">(optional)</span></label><input id="advertiser_name" name="advertiser_name" value="{{ old('advertiser_name', $ad?->advertiser_name) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"></div>
    <div class="lg:col-span-2" x-data="{ preview: '{{ $ad?->imageUrl() }}' }"><label for="image" class="font-bold">Image {{ $ad ? '(leave blank to keep current)' : '' }}</label><input id="image" name="image" type="file" accept="image/jpeg,image/png,image/webp" {{ $ad ? '' : 'required' }} class="mt-2 block w-full" @change="preview = URL.createObjectURL($event.target.files[0])"><p class="mt-2 text-sm text-slate-500">Recommended image size: 1200 × 1500 px. Required aspect ratio: 4:5. PNG, JPG/JPEG, or WebP; maximum 5 MB. The image is cropped with object-cover.</p><div x-show="preview" class="relative mt-4 aspect-[4/5] w-full max-w-xs overflow-hidden rounded-2xl bg-slate-900"><img :src="preview" alt="Advertisement image preview" class="absolute inset-0 h-full w-full object-cover"><span class="absolute bottom-4 right-4 rounded-full bg-indigo-600 px-3 py-1 text-[11px] font-semibold uppercase tracking-wide text-white shadow-sm ring-1 ring-white/20">Sponsored</span></div></div>
    <div class="lg:col-span-2"><label for="destination_url" class="font-bold">Destination URL</label><input id="destination_url" name="destination_url" type="url" required placeholder="https://example.com" value="{{ old('destination_url', $ad?->destination_url) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"><p class="mt-1 text-sm text-slate-500">HTTPS is required.</p></div>
    <div><label for="alt_text" class="font-bold">Alt text</label><input id="alt_text" name="alt_text" required value="{{ old('alt_text', $ad?->alt_text) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"></div>
    <div><label for="cta_label" class="font-bold">CTA label <span class="font-normal text-slate-500">(optional)</span></label><input id="cta_label" name="cta_label" placeholder="Learn more" value="{{ old('cta_label', $ad?->cta_label) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"></div>
    <div><label for="placement" class="font-bold">Placement</label><input id="placement" name="placement" type="number" min="1" required value="{{ old('placement', $ad?->placement ?? 1) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"><p class="mt-1 text-sm text-slate-500">1 places the ad in the first grid position, 2 in the second, and so on. Out-of-range ads append before Add Creator Account.</p></div>
    <div class="flex items-center"><input type="hidden" name="is_active" value="0"><input id="is_active" name="is_active" type="checkbox" value="1" @checked(old('is_active', $ad?->is_active ?? true)) class="rounded border-slate-300"><label for="is_active" class="ml-3 font-bold">Enabled</label></div>
    <div><label for="starts_at" class="font-bold">Starts at <span class="font-normal text-slate-500">(optional)</span></label><input id="starts_at" name="starts_at" type="datetime-local" value="{{ old('starts_at', $ad?->starts_at?->format('Y-m-d\TH:i')) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"></div>
    <div><label for="ends_at" class="font-bold">Ends at <span class="font-normal text-slate-500">(optional)</span></label><input id="ends_at" name="ends_at" type="datetime-local" value="{{ old('ends_at', $ad?->ends_at?->format('Y-m-d\TH:i')) }}" class="mt-2 w-full rounded-xl border-slate-300 dark:bg-slate-950"></div>
</div>
