<section id="daily-journey" data-daily-journey data-authenticated="{{ auth()->check() ? '1' : '0' }}" data-issue-url="{{ route('game.runs.issue') }}" data-login-url="{{ route('login', ['redirect' => route('home').'#daily-journey']) }}" class="border-t border-indigo-400/20 bg-gradient-to-br from-indigo-950 via-slate-950 to-sky-950 px-4 py-8 text-white sm:px-6 lg:px-8">
    <div class="mx-auto max-w-7xl overflow-hidden rounded-3xl border border-white/10 bg-white/5 shadow-2xl">
        <div class="grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center">
            <div><p class="text-xs font-extrabold uppercase tracking-[.22em] text-sky-300">{{ config('daily_journey.title') }}</p><h2 class="mt-2 text-2xl font-extrabold sm:text-3xl">Run today’s trail. Claim tomorrow’s legend.</h2><p class="mt-2 max-w-2xl text-slate-300">Run, jump, duck, and dodge your way to the top of today’s leaderboard.</p>
                <div class="mt-5 flex flex-wrap gap-3 text-sm"><span class="rounded-full bg-white/10 px-3 py-2">Leader: <strong>{{ data_get($game, 'leader.guide.name', 'No score yet') }}</strong> @if(data_get($game,'leader.score'))· {{ number_format(data_get($game,'leader.score')) }}@endif</span><span class="rounded-full bg-white/10 px-3 py-2">Your best: <strong>{{ data_get($game,'me.score') ? number_format(data_get($game,'me.score')) : '—' }}</strong></span><span class="rounded-full bg-white/10 px-3 py-2">Resets in <strong data-game-countdown data-ends-at="{{ $game['day']->ends_at->toIso8601String() }}">--:--:--</strong></span></div>
            </div>
            <div class="flex flex-wrap gap-3 lg:justify-end"><button type="button" data-game-play class="min-h-12 rounded-xl bg-amber-400 px-6 py-3 font-extrabold text-slate-950 shadow-lg hover:bg-amber-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">{{ auth()->check() ? 'Play now' : 'Log in to play' }}</button><a href="{{ route('game.leaderboard') }}" class="min-h-12 rounded-xl border border-white/20 px-5 py-3 text-center font-bold hover:bg-white/10">View leaderboard</a></div>
        </div>
        <div data-game-expanded hidden class="border-t border-white/10 bg-slate-950 p-3 sm:p-5"><div data-game-status class="mb-3 text-sm text-slate-300" role="status">Loading the trail…</div><div data-game-parent class="relative mx-auto aspect-video w-full max-w-6xl overflow-hidden rounded-2xl bg-sky-950" aria-label="Daily Journey Challenge game canvas"></div><div class="mt-3 grid grid-cols-2 gap-3 sm:hidden"><button data-game-jump class="min-h-16 touch-none rounded-2xl bg-indigo-500 text-lg font-extrabold">Jump</button><button data-game-duck class="min-h-16 touch-none rounded-2xl bg-sky-600 text-lg font-extrabold">Duck</button></div><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><p class="text-sm text-slate-300">Space / ↑ jump · ↓ duck · P / Esc pause · M mute. Landscape is recommended.</p><button data-game-close type="button" class="rounded-lg px-3 py-2 font-bold text-slate-300 hover:bg-white/10">Exit game</button></div></div>
    </div>
</section>
