<x-creator-intelligence-layout :title="$contentItem->exists ? 'Edit '.$labels->contentItem : 'Add '.$labels->contentItem">
    <h2 class="mb-5 text-2xl font-extrabold">{{ $contentItem->exists ? 'Edit '.$labels->contentItem : 'Add '.$labels->contentItem }}</h2>
    <form method="POST" action="{{ $contentItem->exists ? route('superadmin.creator-intelligence.content-items.update', $contentItem) : route('superadmin.creator-intelligence.content-items.store') }}" class="ci-form-card max-w-2xl space-y-5">@csrf @if($contentItem->exists) @method('PUT') @endif
        <div><label for="content-channel" class="ci-label">Creator Channel</label><select id="content-channel" name="creator_channel_id" required class="ci-control mt-1 block w-full">@foreach($channels as $channel)<option value="{{ $channel->id }}" @selected(old('creator_channel_id', $contentItem->creator_channel_id) == $channel->id)>{{ $channel->channel_name }} · {{ $channel->content_item_label }}</option>@endforeach</select></div>
        <div><label for="content-subject" class="ci-label">Related {{ $labels->subject }}</label><select id="content-subject" name="subject_id" class="ci-control mt-1 block w-full"><option value="">No related {{ $labels->lowerSubject() }}</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(old('subject_id', $contentItem->subject_id) == $subject->id)>{{ $subject->name }}</option>@endforeach</select></div>
        <div><label for="content-name" class="ci-label">{{ $labels->contentItem }} Name</label><input id="content-name" name="name" required value="{{ old('name', $contentItem->name) }}" aria-describedby="content-name-help @error('name') content-name-error @enderror" @error('name') aria-invalid="true" @enderror class="ci-control mt-1 block w-full @error('name') !border-rose-500 @enderror"><p id="content-name-help" class="ci-help mt-1">Capitalization is preserved exactly as entered after surrounding and repeated whitespace is cleaned.</p>@error('name')<p id="content-name-error" class="ci-error">{{ $message }}</p>@enderror</div>
        <div><label for="content-type" class="ci-label">{{ $labels->contentItem }} Type</label><input id="content-type" name="content_item_type" value="{{ old('content_item_type', $contentItem->content_item_type) }}" class="ci-control mt-1 block w-full"></div>
        <div><label for="content-release-date" class="ci-label">Release Date</label><input id="content-release-date" type="date" name="release_date" value="{{ old('release_date', $contentItem->release_date?->toDateString()) }}" class="ci-control mt-1 block w-full"></div>
        <div><label for="content-notes" class="ci-label">Notes</label><textarea id="content-notes" name="notes" rows="4" class="ci-control mt-1 block w-full">{{ old('notes', $contentItem->notes) }}</textarea></div>
        <label class="flex items-center gap-3 font-bold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $contentItem->is_active ?? true))> Active {{ $labels->contentItem }}</label>
        <button class="ci-button-primary">Save {{ $labels->contentItem }}</button>
    </form>
</x-creator-intelligence-layout>
