import Phaser from 'phaser';

class SeededRandom {
    constructor(seed) { this.state = Number(BigInt(seed) & 0xffffffffn) || 1; }
    next() { let x=this.state; x^=x<<13; x^=x>>>17; x^=x<<5; this.state=x>>>0; return this.state/4294967296; }
    between(min,max){ return min+this.next()*(max-min); }
}

class JourneyScene extends Phaser.Scene {
    constructor(context){ super('journey'); this.ctx=context; }
    create(){
        this.cfg=this.ctx.session.config; this.rng=new SeededRandom(this.ctx.session.seed); this.running=false; this.finished=false; this.manualPaused=false; this.activeMs=0; this.distance=0; this.collectibles=0; this.shieldPickups=0; this.shieldUses=0; this.shield=false; this.tier=1; this.eventLog=[]; this.events.toJSON=()=>this.eventLog; this.nextSpawn=650;
        this.makeArt(); this.cameras.main.setBackgroundColor('#70d6ff');
        this.add.rectangle(640,250,1280,500,0x70d6ff); this.add.circle(1040,110,55,0xffe66d);
        for(let i=0;i<6;i++)this.add.triangle(i*260,510,0,150,130,0,260,150,i%2?0x6cc58f:0x54b878).setOrigin(.5,1);
        this.add.rectangle(640,660,1280,120,0x61412e); this.add.rectangle(640,606,1280,18,0x7bd267);
        this.physics.world.setBounds(0,0,1280,720); this.player=this.physics.add.sprite(215,550,'runner').setOrigin(.5,1).setCollideWorldBounds(true); this.player.body.setSize(56,82).setOffset(12,8); this.player.body.setGravityY(1800);
        this.ground=this.physics.add.staticImage(640,620,'ground').setVisible(false); this.physics.add.collider(this.player,this.ground);
        this.hazards=this.physics.add.group({allowGravity:false,immovable:true}); this.items=this.physics.add.group({allowGravity:false,immovable:true});
        this.physics.add.overlap(this.player,this.hazards,(_,h)=>this.hit(h)); this.physics.add.overlap(this.player,this.items,(_,item)=>this.collect(item));
        this.scoreText=this.add.text(24,22,'Score 0\nDistance 0m',{fontFamily:'Figtree',fontSize:'24px',fontStyle:'bold',color:'#10213b',stroke:'#fff',strokeThickness:5}).setDepth(10);
        this.shieldText=this.add.text(1250,26,'Shield: —',{fontFamily:'Figtree',fontSize:'22px',fontStyle:'bold',color:'#10213b',backgroundColor:'#ffffffcc',padding:{x:12,y:8}}).setOrigin(1,0).setDepth(10);
        this.overlay=this.add.rectangle(640,360,900,390,0x08142c,.92).setDepth(20); this.add.text(640,235,'READY FOR TODAY’S TRAIL?',{fontFamily:'Figtree',fontSize:'35px',fontStyle:'bold',color:'#fff'}).setOrigin(.5).setDepth(21); this.add.text(640,315,'Jump over rocks, fire, and pits.\nDuck under trail signs. Grab stars and a one-hit shield.',{fontFamily:'Figtree',fontSize:'22px',align:'center',color:'#cbd5e1',lineSpacing:10}).setOrigin(.5).setDepth(21); this.startButton=this.add.text(640,430,'START RUN',{fontFamily:'Figtree',fontSize:'28px',fontStyle:'bold',color:'#111827',backgroundColor:'#fbbf24',padding:{x:32,y:16}}).setOrigin(.5).setDepth(21).setInteractive({useHandCursor:true}).on('pointerup',()=>this.startRun());
        this.keys=this.input.keyboard.addKeys({jump:'SPACE',up:'UP',duck:'DOWN',pause:'P',escape:'ESC',mute:'M'}); this.keys.jump.on('down',()=>this.jump()); this.keys.up.on('down',()=>this.jump()); this.keys.duck.on('down',()=>this.setDuck(true)); this.keys.duck.on('up',()=>this.setDuck(false)); this.keys.pause.on('down',()=>this.togglePause()); this.keys.escape.on('down',()=>this.togglePause()); this.keys.mute.on('down',()=>this.ctx.toggleMute());
        this.onJump=()=>this.jump(); this.onDuckStart=()=>this.setDuck(true); this.onDuckEnd=()=>this.setDuck(false); window.addEventListener('daily-journey-jump',this.onJump); window.addEventListener('daily-journey-duck-start',this.onDuckStart); window.addEventListener('daily-journey-duck-end',this.onDuckEnd);
        this.visibility=()=>{if(document.hidden||!document.hasFocus())this.pauseForFocus();}; document.addEventListener('visibilitychange',this.visibility); window.addEventListener('blur',this.visibility); this.events.once('shutdown',()=>this.cleanup());
    }
    makeArt(){const g=this.add.graphics();g.fillStyle(0x4f46e5).fillRoundedRect(0,0,80,90,18);g.fillStyle(0xfde68a).fillCircle(40,22,17);g.fillStyle(0xffffff).fillCircle(34,19,3);g.generateTexture('runner',80,90);g.clear().fillStyle(0x6b4f3b).fillRoundedRect(0,0,78,65,12).lineStyle(6,0x4a3527).strokeRoundedRect(0,0,78,65,12).generateTexture('rock',78,65);g.clear().fillStyle(0xff5b35).fillTriangle(0,70,25,0,45,70).fillStyle(0xffc43d).fillTriangle(20,70,42,18,66,70).generateTexture('fire',70,70);g.clear().fillStyle(0x7c3f1d).fillRoundedRect(0,0,150,34,8).fillStyle(0xffffff).fillRect(15,8,120,18).generateTexture('sign',150,34);g.clear().fillStyle(0x020617).fillEllipse(100,35,200,70).lineStyle(8,0x475569).strokeEllipse(100,35,200,70).generateTexture('pit',200,70);g.clear().fillStyle(0xfbbf24).fillCircle(24,24,22).fillStyle(0xffffff).fillCircle(24,24,8).generateTexture('star',48,48);g.clear().lineStyle(7,0x38bdf8).strokeCircle(30,30,26).fillStyle(0xffffff,.35).fillCircle(30,30,24).generateTexture('shield',60,60);g.clear().fillStyle(0xffffff).fillRect(0,0,1280,30).generateTexture('ground',1280,30);g.destroy();}
    async startRun(){if(this.running)return;try{await this.ctx.post(`${this.ctx.base}/${this.ctx.session.token}/start`,{});}catch(e){this.ctx.status(e.message);return;}this.overlay.destroy();this.startButton.destroy();this.children.list.filter(c=>c.depth===21).forEach(c=>c.destroy());this.running=true;this.log('run_started');this.ctx.status('Run active — good luck!');}
    update(_,delta){if(!this.running||this.finished||this.manualPaused)return;delta=Math.min(delta,50);this.activeMs+=delta;const sec=this.activeMs/1000;const speed=Math.min(this.cfg.maximumSpeed,this.cfg.startingSpeed+this.cfg.acceleration*sec);this.distance+=speed*(delta/1000)/10;this.tier=Math.min(5,1+Math.floor(sec/30));this.nextSpawn-=speed*(delta/1000);if(this.nextSpawn<=0)this.spawnPattern(speed);[...this.hazards.getChildren(),...this.items.getChildren()].forEach(o=>{o.x-=speed*(delta/1000);if(o.x< -220)o.destroy();});const score=Math.floor(this.distance)+this.collectibles*this.cfg.collectibleBonus;this.scoreText.setText(`Score ${score}\nDistance ${Math.floor(this.distance)}m`);if(this.ducking&&this.time.now>this.duckUntil)this.setDuck(false);}
    spawnPattern(speed){const roll=this.rng.next();let type=roll<.22?'rock':roll<.42?'fire':roll<.61?'sign':roll<.78?'pit':roll<.90?'star':'shield';let y=type==='sign'?555:type==='star'?490:type==='shield'?470:type==='pit'?615:600;const o=(type==='star'||type==='shield'?this.items:this.hazards).create(1390,y,type).setOrigin(.5,1);o.kind=type;o.body.setAllowGravity(false);if(type==='sign')o.body.setSize(145,30);if(type==='pit')o.body.setSize(180,38).setOffset(10,25);this.nextSpawn=this.rng.between(Math.max(this.cfg.minGap-speed*.12,300),this.cfg.maxGap);if((type==='rock'||type==='fire')&&this.rng.next()>.45){const star=this.items.create(1390,y-120,'star').setOrigin(.5,1);star.kind='star';star.body.setAllowGravity(false);}}
    jump(){if(!this.running||this.finished||this.manualPaused)return;if(this.player.body.blocked.down){this.setDuck(false);this.player.setVelocityY(-760);this.log('jump');this.ctx.tone(420,.06);}}
    setDuck(value){if(!this.running||this.finished)return;if(value){this.ducking=true;this.duckUntil=this.time.now+900;this.player.setScale(1,.55);this.player.body.setSize(56,42).setOffset(12,48);this.log('duck_started');}else if(this.ducking){this.ducking=false;this.player.setScale(1);this.player.body.setSize(56,82).setOffset(12,8);this.log('duck_ended');}}
    collect(item){if(!item.active)return;if(item.kind==='star'){this.collectibles++;this.log('collectible_collected');this.ctx.tone(720,.05);}else{this.shield=true;this.shieldPickups++;this.shieldText.setText('Shield: READY');this.log('shield_collected');this.ctx.tone(560,.12);}item.destroy();}
    hit(hazard){if(!hazard.active||this.finished)return;if(this.shield&&hazard.kind!=='pit'){this.shield=false;this.shieldUses++;this.shieldText.setText('Shield: —');this.log('shield_used');this.ctx.tone(180,.15);hazard.destroy();return;}this.log(hazard.kind==='pit'?'pit_fall':'collision');this.gameOver();}
    togglePause(){if(!this.running||this.finished)return;this.manualPaused=!this.manualPaused;if(this.manualPaused){this.pauseShade=this.add.rectangle(640,360,1280,720,0x020617,.72).setDepth(40);this.pauseLabel=this.add.text(640,360,'PAUSED\nPress P or Escape to resume',{fontFamily:'Figtree',fontSize:'34px',fontStyle:'bold',align:'center',color:'#fff'}).setOrigin(.5).setDepth(41);this.ctx.status('Paused — press P or Escape to resume.');}else{this.pauseShade?.destroy();this.pauseLabel?.destroy();this.ctx.status('Run resumed.');}}
    pauseForFocus(){if(this.running&&!this.finished&&!this.manualPaused)this.togglePause();}
    async gameOver(){this.finished=true;this.running=false;this.physics.pause();this.log('run_ended');const score=Math.floor(this.distance)+this.collectibles*this.cfg.collectibleBonus;this.ctx.status('Checking your score…');let result;try{result=await this.ctx.post(`${this.ctx.base}/${this.ctx.session.token}/finish`,{score,distance:Number(this.distance.toFixed(2)),duration_ms:Math.floor(this.activeMs),collectible_count:this.collectibles,powerup_pickup_count:this.shieldPickups,powerup_use_count:this.shieldUses,maximum_speed_tier:this.tier,client_version:this.ctx.session.version,events:this.events});}catch(e){result={status:'rejected',message:e.message};}const accepted=result.status==='accepted';this.add.rectangle(640,360,820,340,0x08142c,.94).setDepth(30);this.add.text(640,250,accepted?'RUN ACCEPTED':'RUN NOT RANKED',{fontFamily:'Figtree',fontSize:'38px',fontStyle:'bold',color:accepted?'#6ee7b7':'#fca5a5'}).setOrigin(.5).setDepth(31);this.add.text(640,335,`${score.toLocaleString()} points · ${Math.floor(this.distance)}m\n${accepted?(result.personal_best?'New personal best! ':'')+(result.rank?`Daily rank #${result.rank.rank}`:''):result.message||'This score could not be accepted.'}`,{fontFamily:'Figtree',fontSize:'24px',align:'center',color:'#fff',lineSpacing:12}).setOrigin(.5).setDepth(31);this.add.text(640,440,'PLAY AGAIN',{fontFamily:'Figtree',fontSize:'24px',fontStyle:'bold',color:'#111827',backgroundColor:'#fbbf24',padding:{x:25,y:13}}).setOrigin(.5).setDepth(31).setInteractive({useHandCursor:true}).on('pointerup',()=>this.ctx.restart());this.ctx.status(accepted?'Score accepted.':'Score could not be ranked.');}
    log(e){if(this.eventLog.length<120)this.eventLog.push({t:Math.floor(this.activeMs),e});}
    cleanup(){document.removeEventListener('visibilitychange',this.visibility);window.removeEventListener('blur',this.visibility);window.removeEventListener('daily-journey-jump',this.onJump);window.removeEventListener('daily-journey-duck-start',this.onDuckStart);window.removeEventListener('daily-journey-duck-end',this.onDuckEnd);}
}

export function createGame(parent,session,helpers){return new Phaser.Game({type:Phaser.AUTO,parent,width:1280,height:720,backgroundColor:'#70d6ff',physics:{default:'arcade',arcade:{debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false},scene:[new JourneyScene({...helpers,session})]});}
