<section aria-labelledby="roles-title" class="px-4 py-20 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-7xl"><div class="text-center"><h2 id="roles-title" class="text-3xl font-extrabold sm:text-4xl">One platform. Two powerful roles.</h2></div>
        <div class="mt-12 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
            <article class="rounded-3xl border border-amber-400/30 bg-gradient-to-br from-amber-400/10 to-slate-900 p-6 sm:p-8">
                <p class="text-xs font-black uppercase tracking-[0.18em] text-amber-300">For Guides</p><h3 class="mt-4 text-3xl font-extrabold">Help shape what gets made next</h3>
                <div class="mt-7 rounded-2xl border border-amber-400/20 bg-slate-950/70 p-4"><div class="flex items-center gap-4"><x-how-it-works.demo-avatars size="md" :limit="1" /><div><p class="font-bold">Guide #18</p><p class="text-sm text-amber-300">Founding Guide</p></div></div><dl class="mt-5 grid grid-cols-2 gap-3 text-sm">@foreach ([['Available votes','3/3'],['Favorite creators','7'],['Suggestions submitted','12'],['Published wins','4']] as $stat)<div class="rounded-xl bg-slate-900 p-3"><dd class="text-lg font-black">{{ $stat[1] }}</dd><dt class="text-slate-400">{{ $stat[0] }}</dt></div>@endforeach</dl></div>
                <ul class="mt-7 space-y-3 text-slate-300">@foreach (['Suggest ideas, topics, videos, or links','Vote where your support matters most','Follow the journey from suggestion to publication'] as $benefit)<li class="flex gap-3"><span class="text-amber-300">✓</span>{{ $benefit }}</li>@endforeach</ul>
                <a href="{{ route('home') }}" class="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-amber-400 px-5 py-3 font-extrabold text-slate-950 sm:w-auto">Start guiding</a>
            </article>
            <article class="rounded-3xl border border-indigo-400/40 bg-gradient-to-br from-indigo-500/15 via-slate-900 to-slate-900 p-6 shadow-2xl shadow-indigo-950/30 sm:p-8">
                <p class="text-xs font-black uppercase tracking-[0.18em] text-indigo-300">For Creators</p><h3 class="mt-4 text-3xl font-extrabold">Replace noise with a clear creative signal</h3>
                <div class="mt-7 rounded-2xl border border-indigo-400/20 bg-slate-950/80 p-4"><div class="flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-indigo-500 px-3 py-1.5">Ranked queue</span>@foreach (['Coming Soon','Published','Archive'] as $filter)<span class="rounded-full bg-slate-800 px-3 py-1.5 text-slate-300">{{ $filter }}</span>@endforeach</div>@foreach ([['#1','Live performance breakdown','86'],['#2','Vocal harmony deep dive','71']] as $row)<div class="mt-3 grid grid-cols-[2rem_minmax(0,1fr)_auto] gap-3 rounded-xl border border-slate-800 p-3"><b>{{ $row[0] }}</b><span class="truncate">{{ $row[1] }}</span><b class="text-indigo-300">↑ {{ $row[2] }}</b></div>@endforeach<div class="mt-3 grid grid-cols-3 gap-2 text-center text-xs font-bold"><span class="rounded-lg bg-emerald-500 p-2 text-slate-950">Approve</span><span class="rounded-lg bg-indigo-500/20 p-2 text-indigo-200">Schedule</span><span class="rounded-lg bg-slate-800 p-2">Pass</span></div></div>
                <ul class="mt-7 space-y-3 text-slate-300">@foreach (['Centralize requests from every platform','See what the community supports most','Decide what to approve, schedule, or pass'] as $benefit)<li class="flex gap-3"><span class="text-emerald-300">✓</span>{{ $benefit }}</li>@endforeach</ul>
                @auth<a href="{{ route('creators.create') }}" class="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-indigo-500 px-5 py-3 font-extrabold text-white sm:w-auto">Create your board</a>@else<a href="{{ route('register') }}" class="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-xl bg-indigo-500 px-5 py-3 font-extrabold text-white sm:w-auto">Create your board</a>@endauth
            </article>
        </div>
    </div>
</section>
