@csrf
@if(isset($channel)) @method('PUT') @endif
<div class="grid gap-5 sm:grid-cols-2">
    <div><label for="channel-profile" class="ci-label">Creator Profile</label><select id="channel-profile" name="creator_profile_id" required class="ci-control mt-1 w-full"><option value="">Select a profile</option>@foreach($profiles as $profile)<option value="{{ $profile->id }}" @selected((string) old('creator_profile_id', $channel->creator_profile_id ?? '') === (string) $profile->id)>{{ $profile->display_name }}</option>@endforeach</select></div>
    @foreach(['channel_name'=>'Channel Name','platform'=>'Platform','platform_channel_id'=>'Platform Channel ID','handle'=>'Handle','default_publish_timezone'=>'Publish Timezone','subject_label'=>'Subject Label','content_item_label'=>'Content Item Label','category_label'=>'Category Label'] as $field=>$label)
        @php($default = match($field) {'platform'=>'youtube','default_publish_timezone'=>'America/New_York','subject_label'=>'Subject','content_item_label'=>'Content Item','category_label'=>'Category',default=>''})
        <div><label for="channel-{{ $field }}" class="ci-label">{{ $label }}</label><input id="channel-{{ $field }}" name="{{ $field }}" value="{{ old($field, $channel->{$field} ?? $default) }}" @if(in_array($field,['channel_name','platform','default_publish_timezone','subject_label','content_item_label','category_label'])) required @endif aria-describedby="@if(in_array($field,['subject_label','content_item_label','category_label'])) channel-{{ $field }}-help @endif @error($field) channel-{{ $field }}-error @enderror" @error($field) aria-invalid="true" @enderror class="ci-control mt-1 w-full @error($field) !border-rose-500 @enderror">@if(in_array($field,['subject_label','content_item_label','category_label']))<p id="channel-{{ $field }}-help" class="ci-help mt-1">Controls human-readable terminology throughout Creator Intelligence.</p>@endif @error($field)<p id="channel-{{ $field }}-error" class="ci-error">{{ $message }}</p>@enderror</div>
    @endforeach
    <label class="flex items-center gap-3 font-bold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $channel->is_active ?? true))> Active Channel</label>
</div>
<button class="ci-button-primary mt-6">Save Channel</button>
